### ISSUE TITLE
DeleteAndEnsureBadRequestAsync

### ISSUE THREAD

**Issue by ardalis** [ardalis/HttpClientTestExtensions#24] opened 2022-08-10 15:20 UTC
Same as #10 but for DELETE

**Comment by snowfrogdev** [comment] 2022-08-11 12:19
@ardalis this looks like a duplicate of #17 did you perhaps mean to make this issue for PUT or POST ?

**Comment by ardalis** [comment] 2022-08-11 18:30
Probably - do PUT/POST both have Bad Request options yet? If not, please add.

**Closed as completed** 2022-08-26 14:41 UTC
